name = "dynamic-link-downloader-api"
main = "src/worker.js"
compatibility_date = "2023-12-01"

[env.production]
name = "dynamic-link-downloader-api"

[[env.production.vars]]
NODE_ENV = "production"

[build]
command = "npm run build:worker"
